spring:
  application:
    name: graalvm-project
  datasource:
    username: test_user
    password: password
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/testdb

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          batch_size: 25
        order_updates: true
        order_inserts: true
        batch_versioned_data: true
    open-in-view: false
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:/db/master-changelog.xml
    user: test_user
    password: password