name: Build image

on: push

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run build
        run: |
          docker build --rm --no-cache --progress plain --platform linux/amd64 --tag sensebank/tests:graalvm-project-native .

      - name: Run push
        run: |
          docker push sensebank/tests:graalvm-project-native
